Specify Hugo config file explicitly
The [recent change to use the up-to-date `hugo.toml` name for the Hugo
configuration
file](https://github.com/perladvent/perldotcom/commit/afefaf92482f7e275ce4151c1aecd69f6f809c1b)
unfortunately broke builds for those stuck using older Hugo versions.
This impacted not only those using the `start` `make` target but also
the `legacy-start` target.

The error message when building and starting the site was:

```
Error: Unable to locate config file or config directory. Perhaps you
need to create a new site.
       Run `hugo help new` for details.
```

To avoid such problems for people using Hugo versions v0.109.0 and
older, where the configuration still allows the site to build but can't
find the new default configuration file, it makes sense to specify the
location of the configuration file on the command line explicitly.  This
change also allows the `legacy-start` `make` target to build the site
successfully again.